services:
  db:
    image: postgres:17.6-alpine3.21
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    container_name: catalogdb
    volumes:
      - ./postgres:/var/lib/postgresql/data